services:
    redis:
      image: redis
      container_name: redis
      hostname: redis
      restart: always
      ports:
        - ${REDIS_PORT}:6379
      volumes:
        - ./conf/redis.conf:/etc/redis/redis.conf:rw
        - ./data:/data:rw
      command:
        redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --appendonly yes
  