version: '2'
services:
    rabbitmq:
       hostname: rabbitmq
       environment:
         RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
         RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
       image: "rabbitmq:management"
       restart: always
       volumes:
         - "./data:/var/lib/rabbitmq"
         - "./log:/var/log/rabbitmq/log"
       ports:
         - "15672:15672"
         - "4369:4369"
         - "5672:5672"
         - "25672:25672"
