version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
       - "${PORT}:3306"
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
       - ./data:/var/lib/mysql
       - ./conf/my.cnf:/etc/mysql/conf.d
       - ./source:/docker-entrypoint-initdb.d